apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass 
  annotations:
    tekton.dev/git-0: https://git.personal-crm.ru
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: Ghbdtn2023