import { dateField, selectField, autocompleteField } from '@/utils/fields.js'

const filters = {
  id: 0,
  name: 'Основные',
  type: 'FormDefault',
  detail: false,
  isFilter: true,
  lists: [
    { alias: 'direction_id_logistic', filter: [] },
    { alias: 'manager_id_logistic', filter: [] },
    // { alias: 'object_id_logistic', filter: [] },
    // { alias: 'account_id_logistic', filter: [] },
    { alias: 'status_pt', filter: [] },
    { alias: 'personal_id_logistic', filter: [] },
    { alias: 'doljnost_id_logistic', filter: [] },
    { alias: 'shifts', filter: [] },
    // 'direction_id_logistic',
    // 'manager_id_logistic',
    // 'object_id_logistic',
    // 'account_id_logistic',
    // 'status_pt',
    // 'personal_id_logistic',
    // 'doljnost_id_logistic',
    // 'shifts',
  ],
  // [{alias:"vid_veddomost", filter:[{field:"direction_id", value:"2", type:""}]}]
  alias: 'pt',
  active: false,
  fields: [
    dateField({
      label: 'Период',
      name: 'date_target',
      subtype: 'single',
      placeholder: '',
      classes: [''],
      position: {
        cols: 12,
        sm: 12,
      },
      bootstrapClass: [''],
      alias: 'pt.date_target',
    }),
    // dateField({
    //   label: 'Дата обновления статуса:',
    //   name: 'date_status',
    //   subtype: 'range',
    //   placeholder: '',
    //   classes: [''],
    //   position: {
    //     cols: 12,
    //     sm: 12,
    //   },
    //   bootstrapClass: [''],
    //   alias: 'p.date_status',
    // }),
    // dateField({
    //   label: 'Дата назначения:',
    //   name: 'date_target',
    //   subtype: 'range',
    //   placeholder: '',
    //   classes: [''],
    //   position: {
    //     cols: 12,
    //     sm: 12,
    //   },
    //   bootstrapClass: [''],
    //   alias: 'p.date_target',
    // }),
    selectField({
      label: 'Направление',
      name: 'direction_id',
      subtype: 'single',
      placeholder: '',
      class: [''],
      selectOption: {
        text: 'name',
        value: 'id',
      },
      items: [],
      position: {
        cols: 12,
        sm: 12,
      },
      bootstrapClass: [''],
      alias: 'direction_id_logistic',
    }),
    selectField({
      label: 'Менеджер',
      name: 'manager',
      subtype: 'single',
      placeholder: '',
      class: [''],
      selectOption: {
        text: 'name',
        value: 'id',
      },
      items: [],
      position: {
        cols: 12,
        sm: 12,
      },
      bootstrapClass: [''],
      alias: 'manager_id_logistic',
    }),
    autocompleteField({
      label: 'Объект',
      name: 'object_id',
      subtype: 'single',
      placeholder: '',
      class: [''],
      selectOption: {
        text: 'name',
        value: 'id',
      },
      items: [],
      page: 1,
      search: '',
      url: 'get/pagination_list/object_logistic_id',
      position: {
        cols: 12,
        sm: 12,
      },
      bootstrapClass: [''],
      alias: 'object_logistic',
    }),
    selectField({
      label: 'Бригадир',
      name: 'account_json',
      subtype: 'single',
      placeholder: '',
      class: [''],
      selectOption: {
        text: 'name',
        value: 'id',
      },
      items: [],
      position: {
        cols: 12,
        sm: 12,
      },
      bootstrapClass: [''],
      alias: 'account_id_logistic',
    }),
    selectField({
      label: 'Статус',
      name: 'status',
      subtype: 'single',
      placeholder: '',
      class: [''],
      selectOption: {
        text: 'name',
        value: 'id',
      },
      items: [],
      position: {
        cols: 12,
        sm: 12,
      },
      bootstrapClass: [''],
      alias: 'status_pt',
    }),
    autocompleteField({
      label: 'Линейщик',
      name: 'personal_logistic_id',
      subtype: 'single',
      placeholder: '',
      class: [''],
      selectOption: {
        text: 'name',
        value: 'id',
      },
      items: [],
      page: 1,
      search: '',
      url: 'get/pagination_list/personal_logistic_id',
      position: {
        cols: 12,
        sm: 12,
      },
      bootstrapClass: [''],
      alias: 'personal_logistic_id',
    }),
    selectField({
      label: 'Должность',
      name: 'doljnost_id_logistic',
      subtype: 'single',
      placeholder: '',
      class: [''],
      selectOption: {
        text: 'name',
        value: 'id',
      },
      items: [],
      position: {
        cols: 12,
        sm: 12,
      },
      bootstrapClass: [''],
      alias: 'doljnost_id_logistic',
    }),
    selectField({
      label: 'Смена',
      name: 'shifts',
      subtype: 'single',
      placeholder: '',
      class: [''],
      selectOption: {
        text: 'name',
        value: 'id',
      },
      items: [],
      position: {
        cols: 12,
        sm: 12,
      },
      bootstrapClass: [''],
      alias: 'shifts',
    }),
    //selectField({
    //  id: 0,
    //  name: 'object_name',
    //  value: '',
    //  type: 'select',
    //  subtype: 'multiple',
    //  items: [],
    //  url: 'get/pagination_list/object',
    //  bind: '',
    //  label: 'name',
    //  alias: 'p.object_id',
    //  page: 1,
    //}),
    ////{
    ////  id: 2,
    ////  name: 'device',
    ////  value: '',
    ////  type: 'select',
    ////  endpoint: '',
    ////  bind: '',
    ////  label: '',
    ////},
    ////{
    ////  id: 3,
    ////  name: 'checkbox',
    ////  value: '',
    ////  type: 'checkbox',
    ////  endpoint: '',
    ////  bind: '',
    ////  label: 'Имеет бригадира',
    ////},
    //{
    //  id: 4,
    //  name: 'Date_range',
    //  value: '',
    //  type: 'date',
    //  subtype: 'range',
    //  endpoint: '',
    //  bind: '',
    //  label: 'Range',
    //  menu: false,
    //  alias: 'p.date_target',
    //},
    //{
    //  id: 5,
    //  name: 'date_target',
    //  value: '',
    //  type: 'date',
    //  subsubtype: 'single',
    //  endpoint: '',
    //  bind: '',
    //  label: 'Одиночная дата',
    //  menu: false,
    //  alias: 'p.date_target',
    //},
    //{
    //  id: 5,
    //  name: 'date_target',
    //  value: '',
    //  type: 'date',
    //  subtype: 'period',
    //  endpoint: '',
    //  bind: '',
    //  label: 'Одиночная дата',
    //  menu: false,
    //  alias: 'p.date_target',
    //},
    ////{
    ////  id: 6,
    ////  name: 'Period',
    ////  value: '',
    ////  type: 'Date',
    ////  subtype: 'period',
    ////  period: 'month',
    ////  endpoint: '',
    ////  bind: '',
    ////  label: 'Период ( Месяц )',
    ////  menu: false,
    ////},
  ],
}

export default filters
