<template>
  <Layout>
    <div class="d-flex flex-column flex-grow-1">
      <h1>This is an about page1</h1>
      <TableDefault
        @changeheadershow="changeheadershow"
        :options="tableConfig"
        :filtersConfig="filtersConfig"
      />
    </div>
    <portal-target name="filter" />
  </Layout>
</template>

<script>
function consoleText(row) {
  console.log(row, 2)
  //return 'test'
}

function consoleButton(row) {
  console.log(row, 1)
}

function consolePanel() {
  console.log('panel,button')
}

function searchInputing(field) {
  console.log(field)
}

const tableConfigData = {
  selector: '#mainTable',
  options: {
    selecting: true,
    search: {
      function: searchInputing,
    },
    headerFixed: true,
    url: 'https://dummyjson.com/users',
  },
  panel: {
    buttons: [
      {
        label: 'Обновить',
        class: ['v-table-button--custom'],
        urlIcon:
          'https://uxwing.com/wp-content/themes/uxwing/download/editing-user-action/modify-icon.png',
        function: consolePanel,
        backgroundColor: '#ffffff',
      },
      {
        label: 'Добавить',
        class: ['v-table-button--custom'],
        urlIcon:
          'https://uxwing.com/wp-content/themes/uxwing/download/editing-user-action/modify-icon.png',
        function: consolePanel,
        backgroundColor: '#fff',
      },
      {
        label: 'Скачать',
        class: ['v-table-button--custom'],
        function: consolePanel,
        backgroundColor: '#fff',
      },
    ],
  },
  head: [
    {
      title: 'ID',
      type: 'default',
      align: 'center',
      fixed: {
        value: false,
        position: 'left',
      },
      sorts: [
        {
          type: 'string',
          default: 'asc',
          value: undefined,
          isShow: false,
        },
      ],
      isShow: true,
      width: '20px',
      value: 'id',
      search: {
        field: '',
      },
    },
    {
      title: 'Сотрудник',
      type: 'default',
      align: 'center',
      fixed: {
        value: false,
        position: 'left',
      },
      sorts: [
        {
          type: 'string',
          default: 'asc',
          value: undefined,
          isShow: false,
        },
      ],
      isShow: true,
      width: '10%',
      value: 'firstName',
      search: {
        field: '',
      },
    },
    {
      title: 'Отдел',
      type: 'default',
      align: 'center',
      fixed: {
        value: false,
        position: 'left',
      },
      sorts: [
        {
          type: 'string',
          default: 'asc',
          value: undefined,
          isShow: false,
        },
      ],
      isShow: true,
      width: '5%',
      value: 'company.department',
      search: {
        field: '',
      },
    },
    {
      title: 'Email',
      type: 'default',
      align: 'left',
      fixed: {
        value: false,
        position: undefined,
      },
      sorts: [
        {
          type: 'number',
          default: 'asc',
          value: undefined,
          isShow: false,
        },
      ],
      isShow: true,
      width: '10%',
      value: 'email',
      search: {
        field: '',
      },
    },
    {
      title: 'Телефон',
      type: 'default',
      align: 'center',
      fixed: {
        value: false,
        position: undefined,
      },
      sorts: [
        {
          type: 'date',
          default: 'asc',
          value: undefined,
          isShow: false,
        },
      ],
      isShow: true,
      width: '20%',
      value: 'phone',
      search: {
        field: '',
      },
    },
    {
      title: 'Образование',
      type: 'default',
      align: 'center',
      fixed: {
        value: false,
        position: undefined,
      },
      sorts: [
        {
          type: 'string',
          default: 'asc',
          value: undefined,
          isShow: false,
        },
      ],
      isShow: true,
      width: '10%',
      value: 'university',
      search: {
        field: '',
      },
    },
    {
      title: 'Пол',
      type: 'default',
      align: 'center',
      fixed: {
        value: false,
        position: undefined,
      },
      sorts: [
        {
          type: 'string',
          default: 'asc',
          value: undefined,
          isShow: false,
        },
      ],
      isShow: true,
      width: '10%',
      value: 'gender',
      search: {
        field: '',
      },
    },
    {
      title: 'Мак адрес',
      type: 'default',
      align: 'center',
      fixed: {
        value: false,
        position: undefined,
      },
      sorts: [
        {
          type: 'string',
          default: 'asc',
          value: undefined,
          isShow: false,
        },
      ],
      isShow: true,
      width: '10%',
      value: 'macAddress',
      search: {
        field: '',
      },
    },
    {
      title: 'Домен',
      type: 'default',
      align: 'center',
      fixed: {
        value: false,
        position: undefined,
      },
      sorts: [
        {
          type: 'string',
          default: 'asc',
          value: undefined,
          isShow: false,
        },
      ],
      isShow: true,
      width: '10%',
      value: 'domain',
      search: {
        field: '',
      },
    },
    {
      title: 'День рождения',
      type: 'default',
      align: 'center',
      fixed: {
        value: false,
        position: undefined,
      },
      sorts: [
        {
          type: 'string',
          default: 'asc',
          value: undefined,
          isShow: false,
        },
      ],
      isShow: true,
      width: '10%',
      value: 'birthDate',
      search: {
        field: '',
      },
    },
    {
      title: 'Действия',
      type: 'actions',
      align: 'center',
      fixed: {
        value: false,
        position: 'right',
      },
      isShow: true,
      width: '20px',
      value: 'actions',
      actions: [
        {
          type: 'button',
          urlIcon:
            'https://uxwing.com/wp-content/themes/uxwing/download/editing-user-action/modify-icon.png',
          function: consoleText,
          label: 'Редактировать',
        },
        {
          type: 'button',
          urlIcon:
            'https://icons.veryicon.com/png/o/miscellaneous/operation-scenarios-menu-overview/action-delete-2.png',
          function: consoleButton,
          label: 'Удалить',
        },
      ],
    },
  ],
  data: {
    rows: [],
    totalRows: null,
    pageLength: 30,
    currentPage: 1,
    totalPages: null,
  },
}

import Vue from 'vue'
import TableDefault from '@/components/Table/default/index.vue'
import Layout from '@/layouts/default/index'

export default {
  name: 'Table-View',

  components: {
    TableDefault,
    Layout,
  },
  data() {
    return {
      count: 0,
      tableConfig: tableConfigData,
      employees: [
        {
          employee: 'Иван Иванов',
          department: 'Отдел продаж',
          cost: 2000,
          date: new Date('2021-01-15'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Анна Смирнова',
          department: 'Отдел маркетинга',
          cost: 2500,
          date: new Date('2020-12-10'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Петр Петров',
          department: 'Отдел разработки',
          cost: 3000,
          date: new Date('2021-02-28'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Елена Ковалева',
          department: 'Отдел кадров',
          cost: 2200,
          date: new Date('2021-03-05'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Алексей Соколов',
          department: 'Отдел продаж',
          cost: 2100,
          date: new Date('2020-11-20'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Мария Васильева',
          department: 'Отдел маркетинга',
          cost: 2400,
          date: new Date('2021-04-08'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Сергей Игнатьев',
          department: 'Отдел разработки',
          cost: 3200,
          date: new Date('2021-02-01'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Анастасия Зайцева',
          department: 'Отдел кадров',
          cost: 2300,
          date: new Date('2020-10-05'),
          car: 'A123BC',
          universe: 'Высшее образование',
          univers1: 'Высшее образование',
          univers2: 'univers1123132',
          univers3: 'univers451',
        },
        {
          employee: 'Дмитрий Морозов',
          department: 'Отдел продаж',
          cost: 2050,
          date: new Date('2021-01-10'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Екатерина Соловьева',
          department: 'Отдел маркетинга',
          cost: 2600,
          date: new Date('2020-09-15'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Артем Федоров',
          department: 'Отдел разработки',
          cost: 2800,
          date: new Date('2021-03-20'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Ольга Ефимова',
          department: 'Отдел кадров',
          cost: 2150,
          date: new Date('2021-04-05'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Александра Кузнецова',
          department: 'Отдел продаж',
          cost: 2250,
          date: new Date('2020-08-01'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Игорь Сорокин',
          department: 'Отдел маркетинга',
          cost: 2450,
          date: new Date('2020-11-10'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Максим Костин',
          department: 'Отдел разработки',
          cost: 3300,
          date: new Date('2021-02-15'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Дарья Яковлева',
          department: 'Отдел кадров',
          cost: 2350,
          date: new Date('2020-12-05'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Кирилл Макаров',
          department: 'Отдел продаж',
          cost: 1950,
          date: new Date('2021-03-01'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Алиса Николаева',
          department: 'Отдел маркетинга',
          cost: 2700,
          date: new Date('2020-10-20'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Роман Орлов',
          department: 'Отдел разработки',
          cost: 2900,
          date: new Date('2021-01-05'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Галина Андреева',
          department: 'Отдел кадров',
          cost: 2300,
          date: new Date('2021-04-10'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Иван Иванов',
          department: 'Отдел продаж',
          cost: 2000,
          date: new Date('2021-01-15'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Анна Смирнова',
          department: 'Отдел маркетинга',
          cost: 2500,
          date: new Date('2020-12-10'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Петр Петров',
          department: 'Отдел разработки',
          cost: 3000,
          date: new Date('2021-02-28'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Елена Ковалева',
          department: 'Отдел кадров',
          cost: 2200,
          date: new Date('2021-03-05'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Алексей Соколов',
          department: 'Отдел продаж',
          cost: 2100,
          date: new Date('2020-11-20'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Мария Васильева',
          department: 'Отдел маркетинга',
          cost: 2400,
          date: new Date('2021-04-08'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Сергей Игнатьев',
          department: 'Отдел разработки',
          cost: 3200,
          date: new Date('2021-02-01'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Анастасия Зайцева',
          department: 'Отдел кадров',
          cost: 2300,
          date: new Date('2020-10-05'),
          car: 'A123BC',
          universe: 'Высшее образование',
          univers1: 'Высшее образование',
          univers2: 'univers1123132',
          univers3: 'univers451',
        },
        {
          employee: 'Дмитрий Морозов',
          department: 'Отдел продаж',
          cost: 2050,
          date: new Date('2021-01-10'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Екатерина Соловьева',
          department: 'Отдел маркетинга',
          cost: 2600,
          date: new Date('2020-09-15'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Артем Федоров',
          department: 'Отдел разработки',
          cost: 2800,
          date: new Date('2021-03-20'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Ольга Ефимова',
          department: 'Отдел кадров',
          cost: 2150,
          date: new Date('2021-04-05'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Александра Кузнецова',
          department: 'Отдел продаж',
          cost: 2250,
          date: new Date('2020-08-01'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Игорь Сорокин',
          department: 'Отдел маркетинга',
          cost: 2450,
          date: new Date('2020-11-10'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Максим Костин',
          department: 'Отдел разработки',
          cost: 3300,
          date: new Date('2021-02-15'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Дарья Яковлева',
          department: 'Отдел кадров',
          cost: 2350,
          date: new Date('2020-12-05'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Кирилл Макаров',
          department: 'Отдел продаж',
          cost: 1950,
          date: new Date('2021-03-01'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Алиса Николаева',
          department: 'Отдел маркетинга',
          cost: 2700,
          date: new Date('2020-10-20'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Роман Орлов',
          department: 'Отдел разработки',
          cost: 2900,
          date: new Date('2021-01-05'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Галина Андреева',
          department: 'Отдел кадров',
          cost: 2300,
          date: new Date('2021-04-10'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Иван Иванов',
          department: 'Отдел продаж',
          cost: 2000,
          date: new Date('2021-01-15'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Анна Смирнова',
          department: 'Отдел маркетинга',
          cost: 2500,
          date: new Date('2020-12-10'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Петр Петров',
          department: 'Отдел разработки',
          cost: 3000,
          date: new Date('2021-02-28'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Елена Ковалева',
          department: 'Отдел кадров',
          cost: 2200,
          date: new Date('2021-03-05'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Алексей Соколов',
          department: 'Отдел продаж',
          cost: 2100,
          date: new Date('2020-11-20'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Мария Васильева',
          department: 'Отдел маркетинга',
          cost: 2400,
          date: new Date('2021-04-08'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Сергей Игнатьев',
          department: 'Отдел разработки',
          cost: 3200,
          date: new Date('2021-02-01'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Анастасия Зайцева',
          department: 'Отдел кадров',
          cost: 2300,
          date: new Date('2020-10-05'),
          car: 'A123BC',
          universe: 'Высшее образование',
          univers1: 'Высшее образование',
          univers2: 'univers1123132',
          univers3: 'univers451',
        },
        {
          employee: 'Дмитрий Морозов',
          department: 'Отдел продаж',
          cost: 2050,
          date: new Date('2021-01-10'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Екатерина Соловьева',
          department: 'Отдел маркетинга',
          cost: 2600,
          date: new Date('2020-09-15'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Артем Федоров',
          department: 'Отдел разработки',
          cost: 2800,
          date: new Date('2021-03-20'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Ольга Ефимова',
          department: 'Отдел кадров',
          cost: 2150,
          date: new Date('2021-04-05'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Александра Кузнецова',
          department: 'Отдел продаж',
          cost: 2250,
          date: new Date('2020-08-01'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Игорь Сорокин',
          department: 'Отдел маркетинга',
          cost: 2450,
          date: new Date('2020-11-10'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Максим Костин',
          department: 'Отдел разработки',
          cost: 3300,
          date: new Date('2021-02-15'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Дарья Яковлева',
          department: 'Отдел кадров',
          cost: 2350,
          date: new Date('2020-12-05'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Кирилл Макаров',
          department: 'Отдел продаж',
          cost: 1950,
          date: new Date('2021-03-01'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Алиса Николаева',
          department: 'Отдел маркетинга',
          cost: 2700,
          date: new Date('2020-10-20'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Роман Орлов',
          department: 'Отдел разработки',
          cost: 2900,
          date: new Date('2021-01-05'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Галина Андреева',
          department: 'Отдел кадров',
          cost: 2300,
          date: new Date('2021-04-10'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Иван Иванов',
          department: 'Отдел продаж',
          cost: 2000,
          date: new Date('2021-01-15'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Анна Смирнова',
          department: 'Отдел маркетинга',
          cost: 2500,
          date: new Date('2020-12-10'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Петр Петров',
          department: 'Отдел разработки',
          cost: 3000,
          date: new Date('2021-02-28'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Елена Ковалева',
          department: 'Отдел кадров',
          cost: 2200,
          date: new Date('2021-03-05'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Алексей Соколов',
          department: 'Отдел продаж',
          cost: 2100,
          date: new Date('2020-11-20'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Мария Васильева',
          department: 'Отдел маркетинга',
          cost: 2400,
          date: new Date('2021-04-08'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Сергей Игнатьев',
          department: 'Отдел разработки',
          cost: 3200,
          date: new Date('2021-02-01'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Анастасия Зайцева',
          department: 'Отдел кадров',
          cost: 2300,
          date: new Date('2020-10-05'),
          car: 'A123BC',
          universe: 'Высшее образование',
          univers1: 'Высшее образование',
          univers2: 'univers1123132',
          univers3: 'univers451',
        },
        {
          employee: 'Дмитрий Морозов',
          department: 'Отдел продаж',
          cost: 2050,
          date: new Date('2021-01-10'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Екатерина Соловьева',
          department: 'Отдел маркетинга',
          cost: 2600,
          date: new Date('2020-09-15'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Артем Федоров',
          department: 'Отдел разработки',
          cost: 2800,
          date: new Date('2021-03-20'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Ольга Ефимова',
          department: 'Отдел кадров',
          cost: 2150,
          date: new Date('2021-04-05'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Александра Кузнецова',
          department: 'Отдел продаж',
          cost: 2250,
          date: new Date('2020-08-01'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Игорь Сорокин',
          department: 'Отдел маркетинга',
          cost: 2450,
          date: new Date('2020-11-10'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Максим Костин',
          department: 'Отдел разработки',
          cost: 3300,
          date: new Date('2021-02-15'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Дарья Яковлева',
          department: 'Отдел кадров',
          cost: 2350,
          date: new Date('2020-12-05'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Кирилл Макаров',
          department: 'Отдел продаж',
          cost: 1950,
          date: new Date('2021-03-01'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Алиса Николаева',
          department: 'Отдел маркетинга',
          cost: 2700,
          date: new Date('2020-10-20'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Роман Орлов',
          department: 'Отдел разработки',
          cost: 2900,
          date: new Date('2021-01-05'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
        {
          employee: 'Галина Андреева',
          department: 'Отдел кадров',
          cost: 2300,
          date: new Date('2021-04-10'),
          car: 'A123BC',
          universe1: 'Высшее образование',
          universe2: 'universe1123132',
          universe3: 'Высшее образование',
          universe4: 'universe1123132',
          universe5: 'Высшее образование',
          universe6: 'universe1123132',
          universe7: 'Высшее образование',
          universe8: 'universe1123132',
          universe9: 'Высшее образование',
          universe10: 'universe1123132',
        },
      ],
      output: [],
      filtersConfig: [
        {
          id: 0,
          name: 'employ',
          value: '',
          type: 'select',
          endpoint: '',
          bind: '',
          data: [
            'Alabama',
            'Alaska',
            'American Samoa',
            'Arizona',
            'Arkansas',
            'California',
            'Colorado',
            'Connecticut',
            'Delaware',
            'District of Columbia',
            'Federated States of Micronesia',
            'Florida',
            'Georgia',
            'Guam',
            'Hawaii',
            'Idaho',
            'Illinois',
            'Indiana',
            'Iowa',
            'Kansas',
            'Kentucky',
            'Louisiana',
            'Maine',
            'Marshall Islands',
            'Maryland',
            'Massachusetts',
            'Michigan',
            'Minnesota',
            'Mississippi',
            'Missouri',
            'Montana',
            'Nebraska',
            'Nevada',
            'New Hampshire',
            'New Jersey',
            'New Mexico',
            'New York',
            'North Carolina',
            'North Dakota',
            'Northern Mariana Islands',
            'Ohio',
            'Oklahoma',
            'Oregon',
            'Palau',
            'Pennsylvania',
            'Puerto Rico',
            'Rhode Island',
            'South Carolina',
            'South Dakota',
            'Tennessee',
            'Texas',
            'Utah',
            'Vermont',
            'Virgin Island',
            'Virginia',
            'Washington',
            'West Virginia',
            'Wisconsin',
            'Wyoming',
          ],
        },
        {
          id: 2,
          name: 'device',
          value: '',
          type: 'select',
          endpoint: '',
          bind: '',
          data: [
            'Alabama',
            'Alaska',
            'American Samoa',
            'Arizona',
            'Arkansas',
            'California',
            'Colorado',
            'Connecticut',
            'Delaware',
            'District of Columbia',
            'Federated States of Micronesia',
            'Florida',
            'Georgia',
            'Guam',
            'Hawaii',
            'Idaho',
            'Illinois',
            'Indiana',
            'Iowa',
            'Kansas',
            'Kentucky',
            'Louisiana',
            'Maine',
            'Marshall Islands',
            'Maryland',
            'Massachusetts',
            'Michigan',
            'Minnesota',
            'Mississippi',
            'Missouri',
            'Montana',
            'Nebraska',
            'Nevada',
            'New Hampshire',
            'New Jersey',
            'New Mexico',
            'New York',
            'North Carolina',
            'North Dakota',
            'Northern Mariana Islands',
            'Ohio',
            'Oklahoma',
            'Oregon',
            'Palau',
            'Pennsylvania',
            'Puerto Rico',
            'Rhode Island',
            'South Carolina',
            'South Dakota',
            'Tennessee',
            'Texas',
            'Utah',
            'Vermont',
            'Virgin Island',
            'Virginia',
            'Washington',
            'West Virginia',
            'Wisconsin',
            'Wyoming',
          ],
        },
      ],
    }
  },
  methods: {
    initData() {
      //for (let i = 0  i < 20  i++) {

      //}
      this.employees.map((el) => (el.id = this.generateId()))
      //this.tableConfig.data = this.employees
      this.tableConfig.data.rows = this.employees.slice(0, 20)
      console.log(this.window)
      //this.tableConfig.data.map((el) => )
      const structuredArray = []
      this.tableConfig.data.rows.forEach((row) => {
        if (this.tableConfig.options.selecting) {
          Vue.set(row, 'selected', false)
        }
        structuredArray.push({
          row,
          child: {
            isShow: false,
            data: row,
          },
        })
      })
      this.tableConfig.data.rows = structuredArray
      //this.employees.forEach((row, rowIndex) => {
      //  output.push([])
      //  for(let i = 0  i < chunkSize  i++) {
      //    //output[i] = this.employees.slice(i*chunkSize, i*chunkSize+chunkSize)
      //    output[rowIndex].push([])
      //    if (i === 0) {
      //      output[rowIndex][0] = row
      //    }
      //    // Добавляем новое значение в исх.массив, которое равно - часть массива из входящего массива от i*size (текущая) позиции до текущая + size, это будет массив.
      //  }
      //  this.tableConfig.data = output
      //})
      //for(let i = 0  i < chunkSize  i++) {
      //  //output[i] = this.employees.slice(i*chunkSize, i*chunkSize+chunkSize)
      //  output.push([])
      //  // Добавляем новое значение в исх.массив, которое равно - часть массива из входящего массива от i*size (текущая) позиции до текущая + size, это будет массив.
      //}
    },
    generateId() {
      return 'id' + Math.random().toString(16).slice(2)
    },
    changeheadershow(options) {
      const { headerEl, value } = options

      headerEl.isShow = value
    },
  },
  mounted() {
    console.log(TableDefault)
    //this.initData()
  },
}
</script>
