import { dateField, selectField, autocompleteField } from '@/utils/fields.js'

const filters = {
  id: 0,
  name: 'Основные',
  type: 'FormDefault',
  detail: false,
  isFilter: true,
  active: false,
  fields: [
    selectField({
      label: 'Транслировать для',
      name: 'direction',
      subtype: 'single',
      placeholder: '',
      class: [''],
      isShow: true,
      isShowWhen: ['route', 'unit', 'people'],
      clearable: false,
      selectOption: {
        text: 'name',
        value: 'id',
      },
      items: [
        {
          name: 'Сотрудники',
          value: 'people',
        },
        {
          name: 'Направление',
          value: 'route',
        },
        {
          name: 'Подразделение',
          value: 'unit',
        },
      ],
      position: {
        cols: 12,
        sm: 12,
      },
      bootstrapClass: [''],
    }),
    selectField({
      label: 'Направление',
      name: 'account_id',
      subtype: 'single',
      placeholder: '',
      value: null,
      class: [''],
      isShow: false,
      isShowWhen: ['route'],
      clearable: true,
      selectOption: {
        text: 'name',
        value: 'id',
      },
      items: [],
      url: 'get/account/get_directions',
      position: {
        cols: 12,
        sm: 12,
      },
      bootstrapClass: [''],
      alias: 'p.account_id',
    }),
    selectField({
      label: 'Подразделение',
      name: 'unit',
      subtype: 'multiselect',
      placeholder: '',
      value: null,
      class: [''],
      isShow: false,
      isShowWhen: ['route', 'unit'],
      clearable: true,
      selectOption: {
        text: 'name',
        value: 'id',
      },
      items: [],
      url: 'get/account/get_directions',
      position: {
        cols: 12,
        sm: 6,
      },
      bootstrapClass: [''],
      alias: 'p.account_id',
    }),
    selectField({
      label: 'Объект',
      name: 'account_id',
      subtype: 'multiselect',
      placeholder: '',
      value: null,
      class: [''],
      isShow: false,
      isShowWhen: ['route'],
      clearable: true,
      selectOption: {
        text: 'name',
        value: 'id',
      },
      items: [],
      url: 'get/account/get_directions',
      position: {
        cols: 12,
        sm: 6,
      },
      bootstrapClass: [''],
      alias: 'p.account_id',
    }),
    selectField({
      label: 'Сотрудник',
      name: 'account_id',
      subtype: 'multiselect',
      placeholder: '',
      value: null,
      class: [''],
      isShow: false,
      isShowWhen: ['route', 'unit', 'people'],
      clearable: true,
      selectOption: {
        text: 'name',
        value: 'id',
      },
      items: [],
      url: 'get/account/get_directions',
      position: {
        cols: 12,
        sm: 12,
      },
      bootstrapClass: [''],
      alias: 'p.account_id',
    }),
    // autocompleteField({
    //   label: 'Объект',
    //   name: 'object_id',
    //   subtype: 'single',
    //   placeholder: '',
    //   class: [''],
    //   selectOption: {
    //     text: 'name',
    //     value: 'id',
    //   },
    //   items: [],
    //   page: 1,
    //   search: '',
    //   url: 'get/pagination_list/object',
    //   position: {
    //     cols: 12,
    //     sm: 12,
    //   },
    //   bootstrapClass: [''],
    //   alias: 'p.object_id',
    // }),
    // selectField({
    //   label: 'Направления',
    //   name: 'direction_id',
    //   subtype: 'single',
    //   placeholder: '',
    //   class: [''],
    //   selectOption: {
    //     text: 'name',
    //     value: 'id',
    //   },
    //   items: [],
    //   position: {
    //     cols: 12,
    //     sm: 6,
    //   },
    //   bootstrapClass: [''],
    //   alias: 'p.direction_id',
    // }),
  ],
}

export default filters
