import { get, post, put, del } from '@/api/axios'

export const getTask = (url) => get(url)
export const setTask = (url, data) => post(url, data)
export const setBid = (url, data) => post(url, data)
export const acceptSchets = (url, data) => put(url, data)
export const updateDopData = (url, data) => put(url, data)
export const changeStatusAndData = (url, data) => put(url, data)
export const setFile = (url, data) => post(url, data)
export const updateDataFile = (url, data) => post(url, data)
export const startProcess = (url, data) => post(url, data)
export const sendAmmount = (url, data) => post(url, data)
export const putTask = (url, data) => put(url, data)
export const createZayavka = (url, data) => post(url, data)
export const delCloseSchet = (url) => del(url)
export const sendZayavkaItems = (url, data) => post(url, data)
export const setDataServices = (url, data) => post(url, data)
export const updateTmp = (url, data) => put(url, data)
export const updatePersonalAccess = (url, data) => put(url, data)
export const removeTmp = (url, data) => del(url, data)
export const addTargetService = (url, data) => post(url, data)
